#!/usr/bin/env bash
# plan-review.sh — Categorize PR files by risk level for focused review
# Inspired by Alibaba Open-Code-Review's plan phase pattern:
# "Planning which files need deep inspection vs. surface review saves 40-60% of tool calls"
#
# Usage: plan-review.sh <owner/repo> <pr_number>
# Output: Markdown review plan with files categorized by risk level

set -euo pipefail

if [[ $# -lt 2 ]]; then
  echo "Usage: plan-review.sh <owner/repo> <pr_number>" >&2
  exit 1
fi

REPO="$1"
PR="$2"

export https_proxy="${https_proxy:-http://127.0.0.1:1083}"

# Get changed files via GraphQL API
FILES=$(gh pr view "$PR" --repo "$REPO" --json files --jq '.files[].path' 2>/dev/null || echo "")
if [[ -z "$FILES" ]]; then
  echo "❌ Could not fetch PR files" >&2
  exit 1
fi

# Count total files
TOTAL=$(echo "$FILES" | wc -l)

# If small PR (≤5 files), skip planning — not worth the overhead
if [[ "$TOTAL" -le 5 ]]; then
  echo "📋 **Review Plan**: Small PR ($TOTAL files) — full review, no triage needed."
  echo ""
  echo "Files:"
  echo "$FILES" | sed 's/^/  - `/' | sed 's/$/`/'
  exit 0
fi

echo "📋 **Review Plan** ($TOTAL files changed)"
echo ""

# Categorize files
HIGH_RISK=""
MEDIUM_RISK=""
LOW_RISK=""
HIGH_COUNT=0
MED_COUNT=0
LOW_COUNT=0

while IFS= read -r file; do
  [[ -z "$file" ]] && continue
  
  basename=$(basename "$file")
  dirpath=$(dirname "$file")
  
  # LOW RISK first (most specific patterns)
  case "$file" in
    *.md | *.txt | *.mdx | *.rst | \
    *test* | *spec* | *__tests__* | *__mocks__* | *fixtures* | \
    *.css | *.scss | *.less | \
    *.svg | *.png | *.jpg | *.gif | *.ico | \
    *package-lock* | *pnpm-lock* | *yarn.lock | \
    *.d.ts | *generated* | *__generated__* | \
    .gitignore | .eslintrc* | .prettierrc* | tsconfig* | *.config.js | *.config.ts | \
    LICENSE* | CHANGELOG*)
      LOW_RISK="$LOW_RISK\n  - \`$file\`"
      ((LOW_COUNT++)) || true
      continue
      ;;
  esac
  
  # HIGH RISK patterns
  case "$file" in
    *auth* | *login* | *session* | *token* | *credential* | *secret* | *password* | \
    *middleware* | *guard* | *permission* | *rbac* | *acl* | *policy* | \
    *route*.ts | *route*.js | *route*.go | *router* | \
    *api/* | *server/src/* | *handler* | *controller* | \
    *migration* | *schema*.sql | *schema*.ts | *model*.ts | *model*.go | \
    */db/* | */database/* | *prisma* | *drizzle* | \
    *payment* | *billing* | *stripe* | *webhook* | \
    *.env* | *Caddyfile* | *nginx* | *docker* | \
    *crypto* | *hash* | *encrypt* | *decrypt* | \
    */ws/* | *websocket* | *dispatcher*)
      HIGH_RISK="$HIGH_RISK\n  - \`$file\`"
      ((HIGH_COUNT++)) || true
      continue
      ;;
  esac
  
  # MEDIUM RISK: Everything else
  MEDIUM_RISK="$MEDIUM_RISK\n  - \`$file\`"
  ((MED_COUNT++)) || true
  
done <<< "$FILES"

# Output plan
if [[ -n "$HIGH_RISK" ]]; then
  echo "### 🔴 High Risk ($HIGH_COUNT files) — Deep Review Required"
  echo "Auth, security, API, database, middleware, WebSocket, or sensitive config."
  echo "**Spend most review effort here.** Check for: injection, auth bypass, data leaks, race conditions."
  echo -e "$HIGH_RISK"
  echo ""
fi

if [[ -n "$MEDIUM_RISK" ]]; then
  echo "### 🟡 Medium Risk ($MED_COUNT files) — Standard Review"
  echo "Business logic, UI components, utilities, state management."
  echo "Check for: correctness, edge cases, maintainability."
  echo -e "$MEDIUM_RISK"
  echo ""
fi

if [[ -n "$LOW_RISK" ]]; then
  echo "### 🟢 Low Risk ($LOW_COUNT files) — Surface Scan"
  echo "Tests, docs, configs, assets, generated files."
  echo "Quick check: do tests actually test what changed? Are docs accurate? Don't deep-dive."
  echo -e "$LOW_RISK"
  echo ""
fi

echo "---"
echo "_Review plan generated by plan-review.sh (Alibaba OCR plan phase pattern)_"
